### ISSUE TITLE
Baseline cadence survey including northern ecliptic plane

### ISSUE THREAD

**Issue by migueldvb** [lsst/sims_operations#43]
In addition to the survey simulations that are described in the [benchmark surveys webpage](http://lsst.org/scientists/simulations/opsim/opsim-v335-benchmark-surveys), it would be useful to run an alternative simulation using the same baseline universal cadence for the sky with airmass < 1.4 and include the northern part of the ecliptic plane. The northern ecliptic proposal has about 7% of time in the baseline strategy that in this simulation would be added to the time of the universal cadence survey. I think it is interesting to see if the level completeness of solar system objects increases significantly . Analysis of the completeness of different populations and the metrics relevant for evaluating the other science projects can then be compared with the results from the current baseline simulations.

**Comment by mareuter** [comment]
Thank you for your interest in the Operations Simulator. To add your request to the official queue of simulations, please visit [here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/README.md) and  add a new suggestion.
